//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCrawler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebCrawler.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\FCIS\2nd\1st term\Data Structures\Project\Web Crawler\WindowsFormsApplication1\Resources\loading.png.
        /// </summary>
        internal static string Loading_Picture1 {
            get {
                return ResourceManager.GetString("Loading_Picture1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\FCIS\2nd\1st term\Data Structures\Project\Web Crawler\WindowsFormsApplication1\Resources\loading30.png.
        /// </summary>
        internal static string Loading_Picture2 {
            get {
                return ResourceManager.GetString("Loading_Picture2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\FCIS\2nd\1st term\Data Structures\Project\Web Crawler\WindowsFormsApplication1\Resources\loading60.png.
        /// </summary>
        internal static string Loading_Picture3 {
            get {
                return ResourceManager.GetString("Loading_Picture3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\FCIS\2nd\1st term\Data Structures\Project\Web Crawler\WindowsFormsApplication1\Resources\loading.png.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
    }
}
